import {applyMatches,applyPinyinReview,mergeRules,contextualFix} from './cleaner-core.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const app={view:'clean',mode:'balanced',file:null,sourceText:'',encoding:'',rules:null,scan:null,adGroups:[],adDecisions:{},adFinalText:'',pinyin:null,pinyinDecisions:{},finalText:'',dirty:0,worker:null,job:0};
const toast=msg=>{const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2600)};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('zh-CN');
const LS_RULES='novelCleaner.localRules.v1',LS_GIT='novelCleaner.git.v1';
function setView(v){app.view=v;$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${v}`));if(v==='rules')renderRules();}
function setRuleStatus(ok,text){$('#ruleStatus').className='dot '+(ok?'ready':'error');$('#ruleStatusText').textContent=text;}
function dirty(n=1){app.dirty+=n;$('#pendingSync').textContent=`待同步 ${fmt(app.dirty)}`;$('#pendingSync').classList.toggle('dirty',app.dirty>0);persistLocalRules();renderRuleCounts();}
function persistLocalRules(){try{localStorage.setItem(LS_RULES,JSON.stringify(app.rules));}catch(e){console.warn(e)}}
function readLocalRules(){try{return JSON.parse(localStorage.getItem(LS_RULES)||'null')}catch{return null}}
async function loadRules(){try{const r=await fetch(`./rules.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const remote=await r.json(),local=readLocalRules();app.rules=local?mergeRules(remote,local):remote;setRuleStatus(true,`规则 v${app.rules.version||1} · 本地可用`);persistLocalRules();renderRuleCounts();}catch(e){const local=readLocalRules();if(local){app.rules=local;setRuleStatus(true,'使用浏览器本地规则');renderRuleCounts();}else{setRuleStatus(false,'规则加载失败');toast('rules.json 加载失败：'+e.message);}}}
function renderRuleCounts(){if(!app.rules)return;$('#rAd').textContent=fmt(app.rules.adExact?.length);$('#rGarble').textContent=fmt(app.rules.garbleSamples?.length);$('#rPinyin').textContent=fmt(app.rules.pinyinFixes?.length);$('#rKeep').textContent=fmt((app.rules.keepFields?.length||0)+(app.rules.englishKeep?.length||0)+(app.rules.pinyinKeep?.length||0));}
function runWorker(type,payload){if(!app.worker)app.worker=new Worker('./worker.js',{type:'module'});const id=++app.job;return new Promise((resolve,reject)=>{const handler=e=>{if(e.data?.id!==id)return;app.worker.removeEventListener('message',handler);e.data.ok?resolve(e.data.result):reject(new Error(e.data.error||'Worker error'));};app.worker.addEventListener('message',handler);app.worker.postMessage({id,type,...payload});});}
function setProgress(on,text='正在扫描…',pct=15){$('#progressPanel').classList.toggle('hidden',!on);$('#progressText').textContent=text;$('#progressPercent').textContent=pct+'%';$('#progressBar').style.width=pct+'%';}
function decodeScore(s){const repl=(s.match(/�/g)||[]).length,ctrl=(s.match(/[\u0000-\u0008\u000E-\u001F]/g)||[]).length,han=(s.match(/[\u3400-\u9fff]/g)||[]).length;return han*0.02-repl*10-ctrl*4;}
async function decodeFile(file){const ab=await file.arrayBuffer(),u=new Uint8Array(ab);if(u[0]===0xef&&u[1]===0xbb&&u[2]===0xbf)return {text:new TextDecoder('utf-8').decode(ab),encoding:'UTF-8 BOM'};if((u[0]===0xff&&u[1]===0xfe)||(u[0]===0xfe&&u[1]===0xff))return {text:new TextDecoder('utf-16').decode(ab),encoding:'UTF-16'};try{return {text:new TextDecoder('utf-8',{fatal:true}).decode(ab),encoding:'UTF-8'}}catch{}const candidates=[];for(const enc of ['gb18030','big5'])try{const t=new TextDecoder(enc).decode(ab);candidates.push({text:t,encoding:enc.toUpperCase(),score:decodeScore(t)})}catch{}if(candidates.length){candidates.sort((a,b)=>b.score-a.score);return candidates[0]}return {text:new TextDecoder('utf-8').decode(ab),encoding:'UTF-8(replace)'};}
function resetSession(){app.scan=null;app.adGroups=[];app.adDecisions={};app.pinyin=null;app.pinyinDecisions={};app.finalText='';$('#summaryPanel').classList.add('hidden');$('#donePanel').classList.add('hidden');$('#adReviewSection').classList.add('hidden');$('#pinyinReviewSection').classList.add('hidden');$('#reviewEmpty').classList.remove('hidden');updateReviewBadge();}
function groupReviews(rows){const m=new Map();for(const x of rows||[]){let g=m.get(x.field);if(!g){g={field:x.field,kind:x.kind,score:x.score,reason:x.reason,count:0,contexts:[]};m.set(x.field,g)}g.count++;g.score=Math.max(g.score,x.score);if(g.contexts.length<4)g.contexts.push(x.originalLine);}return [...m.values()].sort((a,b)=>b.score-a.score||b.count-a.count);}
function updateReviewBadge(){const a=app.adGroups.length,p=app.pinyin?.review?.length||0,n=a+p;$('#reviewBadge').textContent=n;$('#reviewBadge').classList.toggle('hidden',!n);}
function highlight(line,field){const i=line.indexOf(field);if(i<0)return esc(line);return esc(line.slice(0,i))+`<mark>${esc(field)}</mark>`+esc(line.slice(i+field.length));}
function renderAdReview(){const root=$('#adReviewList');root.innerHTML='';app.adGroups.forEach(g=>{app.adDecisions[g.field]??='keep';const el=document.createElement('article');el.className='review-card';el.innerHTML=`<div><div class="field">${esc(g.field)}</div><div class="reason">${esc(g.kind)} · CONF ${Number(g.score).toFixed(1)} · ×${g.count} · ${esc(g.reason||'')}</div></div><div class="choices"><button class="delete" data-a="delete">删除</button><button class="keep active" data-a="keep">保留</button></div><div class="context">${highlight(g.contexts[0]||'',g.field)}</div>`;const btns=[...el.querySelectorAll('.choices button')];btns.forEach(b=>b.onclick=()=>{app.adDecisions[g.field]=b.dataset.a;btns.forEach(x=>x.classList.toggle('active',x===b));});root.appendChild(el)});$('#adReviewSection').classList.toggle('hidden',!app.adGroups.length);$('#reviewEmpty').classList.toggle('hidden',!!app.adGroups.length);}
function renderPinyinReview(){const root=$('#pinyinReviewList');root.innerHTML='';const rows=app.pinyin?.review||[];rows.forEach((c,i)=>{app.pinyinDecisions[i]??='keep';const el=document.createElement('article');el.className='review-card';el.innerHTML=`<div><div class="field">${esc(c.original)} <span style="color:var(--acid)">→</span> ${esc(c.replacement)}</div><div class="reason">${Math.round((c.confidence||0)*100)}% · ${esc(c.reason||'拼音候选')}</div></div><div class="choices"><button class="replace" data-a="replace">替换</button><button class="keep active" data-a="keep">保留</button><button data-a="english">英文/名称</button></div><div class="context">${esc(c.context||'')}</div>`;const btns=[...el.querySelectorAll('.choices button')];btns.forEach(b=>b.onclick=()=>{app.pinyinDecisions[i]=b.dataset.a;btns.forEach(x=>x.classList.toggle('active',x===b));});root.appendChild(el)});$('#pinyinReviewSection').classList.toggle('hidden',!rows.length);$('#reviewEmpty').classList.toggle('hidden',!!rows.length||!!app.adGroups.length);updateReviewBadge();}
function learnPinyinFix(fix){if(!fix?.source||!fix?.target)return;app.rules.pinyinFixes??=[];const x=app.rules.pinyinFixes.find(z=>z.source===fix.source&&z.target===fix.target);if(x)x.count=(x.count||1)+1;else app.rules.pinyinFixes.push({source:fix.source,target:fix.target,count:1});}
function learnFromSession(){let changed=0;const garbleKinds=new Set(['obfuscated_ad','standalone_pollution_line','pollution_prefix','group_context_ad','pollution']);for(const m of app.scan?.auto||[]){if(m.kind==='learned_exact')continue;if(garbleKinds.has(m.kind)){app.rules.garbleSamples??=[];if(!app.rules.garbleSamples.includes(m.field)){app.rules.garbleSamples.push(m.field);changed++;}}else if(!['html_tag','web_link','image_link','image_html_line','roman_numeral'].includes(m.kind)){app.rules.adExact??=[];if(!app.rules.adExact.includes(m.field)){app.rules.adExact.push(m.field);changed++;}}}
  for(const g of app.adGroups){const d=app.adDecisions[g.field]||'keep';if(d==='delete'){const arr=garbleKinds.has(g.kind)?(app.rules.garbleSamples??=[]):(app.rules.adExact??=[]);if(!arr.includes(g.field)){arr.push(g.field);changed++;}}else{app.rules.keepFields??=[];if(!app.rules.keepFields.includes(g.field)){app.rules.keepFields.push(g.field);changed++;}}}
  for(const c of app.pinyin?.auto||[]){const before=app.rules.pinyinFixes?.length||0;learnPinyinFix(c.learnFix||{source:c.original,target:c.replacement});if((app.rules.pinyinFixes?.length||0)>before)changed++;}
  for(const [k,v] of Object.entries(app.pinyinDecisions)){const i=+k,c=app.pinyin?.review?.[i];if(!c)continue;if(v==='replace'){const before=app.rules.pinyinFixes?.length||0;learnPinyinFix(c.learnFix||contextualFix(c,c.context||''));if((app.rules.pinyinFixes?.length||0)>before)changed++;}else if(v==='english'){app.rules.englishKeep??=[];if(!app.rules.englishKeep.some(x=>String(x).toLowerCase()===c.original.toLowerCase())){app.rules.englishKeep.push(c.original);changed++;}}else{app.rules.pinyinKeep??=[];const key=c.learnFix?.source||c.original;if(!app.rules.pinyinKeep.includes(key)){app.rules.pinyinKeep.push(key);changed++;}}}
  app.rules.stats??={};app.rules.stats.learnedBooks=(app.rules.stats.learnedBooks||0)+1;app.rules.stats.adExact=app.rules.adExact?.length||0;app.rules.stats.garbleSamples=app.rules.garbleSamples?.length||0;app.rules.stats.pinyinFixes=app.rules.pinyinFixes?.length||0;if(changed||1)dirty(Math.max(1,changed));return changed;}
async function scan(){if(!app.file||!app.rules)return;resetSession();setProgress(true,'读取并识别 TXT 编码…',10);$('#scanBtn').disabled=true;try{const d=await decodeFile(app.file);app.sourceText=d.text;app.encoding=d.encoding;setProgress(true,`本地扫描 ${fmt(d.text.length)} 字符…`,35);await new Promise(r=>setTimeout(r,50));const publishers=$('#publisherInput').value.split(/[,，;；\n]/).map(x=>x.trim()).filter(Boolean);const result=await runWorker('scan',{text:d.text,rules:app.rules,opts:{mode:app.mode,publishers,preserveBlank:true}});app.scan=result;app.adGroups=groupReviews(result.review);setProgress(true,'扫描完成，正在准备复核…',100);setTimeout(()=>setProgress(false),280);$('#summaryPanel').classList.remove('hidden');$('#summaryTitle').textContent=`${app.file.name} · ${d.encoding}`;$('#mAuto').textContent=fmt(result.auto.length);$('#mReview').textContent=fmt(app.adGroups.length);$('#mPinyinAuto').textContent='—';$('#mPinyinReview').textContent='—';$('#summaryNote').textContent=app.adGroups.length?'先复核广告/乱码候选，再执行拼音修复。':'广告阶段无需人工复核，可直接进入拼音修复。';renderAdReview();updateReviewBadge();toast(`扫描完成：自动清理 ${result.auto.length} 处`);}catch(e){console.error(e);toast('扫描失败：'+e.message);setProgress(false);}finally{$('#scanBtn').disabled=false;}}
async function startPinyinStage(){if(!app.scan)return;setView('review');const selected=app.scan.review.filter(m=>(app.adDecisions[m.field]||'keep')==='delete');app.adFinalText=applyMatches(app.sourceText,[...app.scan.auto,...selected],true);$('#adReviewSection').classList.add('hidden');if(!$('#pinyinToggle').checked){app.pinyin={text:app.adFinalText,auto:[],review:[]};finishSession();return;}$('#reviewEmpty').classList.remove('hidden');$('#reviewEmpty').textContent='正在加载离线拼音模型并分析正文…';try{const p=await runWorker('pinyin',{text:app.adFinalText,rules:app.rules});app.pinyin=p;app.pinyinDecisions={};$('#mPinyinAuto').textContent=fmt(p.auto.length);$('#mPinyinReview').textContent=fmt(p.review.length);renderPinyinReview();if(!p.review.length){finishSession();}else toast(`拼音：自动修复 ${p.auto.length}，待复核 ${p.review.length}`);}catch(e){toast('拼音修复失败，已保留广告清理结果');app.pinyin={text:app.adFinalText,auto:[],review:[]};finishSession();}}
function finishSession(){if(!app.pinyin)return;app.finalText=applyPinyinReview(app.pinyin.text,app.pinyin.review||[],app.pinyinDecisions);const learned=learnFromSession();$('#pinyinReviewSection').classList.add('hidden');$('#reviewEmpty').classList.add('hidden');$('#donePanel').classList.remove('hidden');$('#doneText').textContent=`广告自动清理 ${fmt(app.scan?.auto?.length)} 处；拼音自动修复 ${fmt(app.pinyin?.auto?.length)} 处；本次新增/确认学习约 ${fmt(learned)} 条。规则尚未上传，只有点击“保存学习规则到 GitHub”才会联网。`;setView('clean');updateReviewBadge();toast('处理完成，可下载最终 TXT');}
function downloadBlob(content,name,type='text/plain;charset=utf-8'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function renderRules(){if(!app.rules)return;renderRuleCounts();const q=$('#ruleSearch').value.trim().toLowerCase(),rows=[];for(const x of app.rules.adExact||[])rows.push(['广告',x]);for(const x of app.rules.garbleSamples||[])rows.push(['乱码',x]);for(const x of app.rules.pinyinFixes||[])rows.push(['拼音',`${x.source} → ${x.target} ×${x.count||1}`]);for(const x of app.rules.keepFields||[])rows.push(['保留',x]);for(const x of app.rules.englishKeep||[])rows.push(['英文',x]);const filtered=rows.filter(r=>!q||r.join(' ').toLowerCase().includes(q)).slice(0,800);$('#ruleList').innerHTML=filtered.length?filtered.map(r=>`<div class="rule-row"><span>${esc(r[0])}</span><code>${esc(r[1])}</code></div>`).join(''):'<div class="empty">没有匹配规则</div>';}
function gitCfg(){return {repo:$('#repoInput').value.trim(),branch:$('#branchInput').value.trim()||'main',token:$('#tokenInput').value.trim()}}
function persistGit(){const c=gitCfg();localStorage.setItem(LS_GIT,JSON.stringify(c));}
function loadGit(){try{const c=JSON.parse(localStorage.getItem(LS_GIT)||'null');if(c){$('#repoInput').value=c.repo||$('#repoInput').value;$('#branchInput').value=c.branch||'main';$('#tokenInput').value=c.token||'';}}catch{}}
function ghHeaders(token){const h={'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};if(token)h.Authorization=`Bearer ${token}`;return h;}
function b64Text(s){const bytes=new TextEncoder().encode(s);let bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(bin)}
function textB64(s){const bin=atob(String(s).replace(/\s/g,'')),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return new TextDecoder().decode(u)}
async function fetchRemoteRules(cfg){const [owner,repo]=cfg.repo.split('/');if(!owner||!repo)throw new Error('仓库格式应为 owner/repo');const url=`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents/rules.json?ref=${encodeURIComponent(cfg.branch)}`;const r=await fetch(url,{headers:ghHeaders(cfg.token),cache:'no-store'});if(!r.ok)throw new Error(`读取 rules.json 失败：HTTP ${r.status}`);const j=await r.json();return {rules:JSON.parse(textB64(j.content)),sha:j.sha,url:`https://api.github.com/repos/${owner}/${repo}/contents/rules.json`};}
async function testGit(){const c=gitCfg();persistGit();try{const r=await fetch(`https://api.github.com/repos/${c.repo}`,{headers:ghHeaders(c.token)});if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json();$('#gitResult').textContent=`连接成功：${j.full_name} · 默认分支 ${j.default_branch}`;toast('GitHub 连接成功');}catch(e){$('#gitResult').textContent='连接失败：'+e.message;toast('GitHub 连接失败');}}
async function saveGit(){if(!app.rules)return;const c=gitCfg();if(!c.token){toast('请先填写 Fine-grained Token');setView('settings');return;}persistGit();try{$('#gitResult').textContent='正在读取 GitHub 最新 rules.json 并合并…';const remote=await fetchRemoteRules(c);let merged=mergeRules(remote.rules,app.rules);merged.version=Math.max(+remote.rules.version||0,+app.rules.version||0)+1;merged.updatedAt=new Date().toISOString();merged.stats={...(merged.stats||{}),learnedBooks:Math.max(remote.rules.stats?.learnedBooks||0,app.rules.stats?.learnedBooks||0),adExact:merged.adExact?.length||0,garbleSamples:merged.garbleSamples?.length||0,pinyinFixes:merged.pinyinFixes?.length||0};const body={message:`rules: update personal learning v${merged.version}`,content:b64Text(JSON.stringify(merged,null,2)),sha:remote.sha,branch:c.branch};const r=await fetch(remote.url,{method:'PUT',headers:{...ghHeaders(c.token),'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`写入失败：HTTP ${r.status} ${(await r.text()).slice(0,200)}`);app.rules=merged;app.dirty=0;persistLocalRules();$('#pendingSync').textContent='待同步 0';$('#pendingSync').classList.remove('dirty');$('#gitResult').textContent=`保存成功：rules.json v${merged.version}。GitHub Pages 通常会在几十秒内更新。`;renderRuleCounts();toast('学习规则已保存到 GitHub');}catch(e){console.error(e);$('#gitResult').textContent='保存失败：'+e.message;toast('GitHub 保存失败');}}
async function pullGit(){const c=gitCfg();persistGit();if(app.dirty&&!confirm('本机还有未同步学习。继续将以 GitHub 规则为准，是否继续？'))return;try{const remote=await fetchRemoteRules(c);app.rules=remote.rules;app.dirty=0;persistLocalRules();renderRuleCounts();$('#pendingSync').textContent='待同步 0';$('#pendingSync').classList.remove('dirty');$('#gitResult').textContent=`已从 GitHub 恢复 rules.json v${app.rules.version||1}`;toast('规则恢复完成');}catch(e){$('#gitResult').textContent='恢复失败：'+e.message;toast('恢复失败');}}
function bind(){
  $$('.tab').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#backCleanBtn').onclick=()=>setView('clean');
  $$('#modeGroup button').forEach(b=>b.onclick=()=>{$$('#modeGroup button').forEach(x=>x.classList.toggle('active',x===b));app.mode=b.dataset.mode});
  $('#fileInput').onchange=()=>{const f=$('#fileInput').files?.[0];if(!f)return;app.file=f;resetSession();$('#fileTitle').textContent=f.name;$('#fileMeta').textContent=`${(f.size/1048576).toFixed(2)} MB · 仅本地读取`;$('#scanBtn').disabled=false;};
  $('#scanBtn').onclick=scan;$('#goReviewBtn').onclick=()=>{setView('review');if(app.adGroups.length){renderAdReview()}else startPinyinStage()};
  $('#keepAllAdBtn').onclick=()=>{for(const g of app.adGroups)app.adDecisions[g.field]='keep';renderAdReview();toast('广告候选全部保留')};$('#applyAdBtn').onclick=startPinyinStage;
  $('#keepAllPinyinBtn').onclick=()=>{(app.pinyin?.review||[]).forEach((_,i)=>app.pinyinDecisions[i]='keep');renderPinyinReview();toast('拼音候选全部保持原文')};$('#finishBtn').onclick=finishSession;
  $('#downloadBtn').onclick=()=>{if(!app.finalText)return;const stem=(app.file?.name||'novel.txt').replace(/\.txt$/i,'');downloadBlob('\ufeff'+app.finalText,`${stem}_去广告.txt`)};$('#saveGitQuickBtn').onclick=saveGit;
  $('#ruleSearch').oninput=renderRules;$('#exportRulesBtn').onclick=()=>downloadBlob(JSON.stringify(app.rules,null,2),'rules.json','application/json;charset=utf-8');$('#importRulesInput').onchange=async()=>{const f=$('#importRulesInput').files?.[0];if(!f)return;try{const j=JSON.parse(await f.text());app.rules=mergeRules(app.rules,j);dirty(1);renderRules();toast('规则已导入并合并')}catch{toast('不是有效的 rules.json')}};
  $('#repoInput').onchange=persistGit;$('#branchInput').onchange=persistGit;$('#tokenInput').onchange=persistGit;$('#testGitBtn').onclick=testGit;$('#saveGitBtn').onclick=saveGit;$('#pullGitBtn').onclick=pullGit;
}
async function boot(){bind();loadGit();await loadRules();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn);}
boot();
