import {applyMatches,applyPinyinReview,mergeRules,contextualFix} from './cleaner-core.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],fmt=n=>Number(n||0).toLocaleString('zh-CN');
const A={mode:'balanced',file:null,source:'',rules:null,base:null,personal:null,scan:null,groups:[],ad:{},pinyin:null,pd:{},final:'',dirty:0,w:null,id:0};
const LS='novelCleaner.localRules.v2',LG='novelCleaner.git.v1',B=['builtin-ad-1.json','builtin-ad-2.json','builtin-ad-3.json','builtin-ad-4.json','builtin-ad-5.json'];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt',"'":'&#39;','"':'&quot;'}[c]));
function toast(s){let e=$('#toast');e.textContent=s;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),2400)}
function view(v){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${v}`));if(v==='rules')renderRules()}
function empty(){return{schema:1,version:1,adExact:[],garbleSamples:[],keepFields:[],pinyinFixes:[],pinyinKeep:[],englishKeep:[],stats:{learnedBooks:0}}}
function subtract(all,base){const o=empty(),sub=(a,b)=>{let s=new Set(b||[]);return(a||[]).filter(x=>!s.has(x))};o.version=A.personal?.version||1;o.updatedAt=new Date().toISOString();for(const k of['adExact','garbleSamples','keepFields','pinyinKeep','englishKeep'])o[k]=sub(all?.[k],base?.[k]);const bm=new Set((base?.pinyinFixes||[]).map(x=>x.source+'\0'+x.target));o.pinyinFixes=(all?.pinyinFixes||[]).filter(x=>!bm.has(x.source+'\0'+x.target));o.stats={learnedBooks:all?.stats?.learnedBooks||0,adExact:o.adExact.length,garbleSamples:o.garbleSamples.length,pinyinFixes:o.pinyinFixes.length};return o}
function persist(){A.personal=subtract(A.rules,A.base);localStorage.setItem(LS,JSON.stringify(A.personal));counts()}
function dirty(n=1){A.dirty+=n;$('#pendingSync').textContent=`待同步 ${fmt(A.dirty)}`;$('#pendingSync').classList.toggle('dirty',A.dirty>0);persist()}
async function j(url){let r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(`${url} HTTP ${r.status}`);return r.json()}
async function loadRules(){try{let [personal,...bs]=await Promise.all([j(`./rules.json?t=${Date.now()}`),...B.map(x=>j('./'+x))]),base=empty();for(const b of bs)base=mergeRules(base,b);let local=null;try{local=JSON.parse(localStorage.getItem(LS)||'null')}catch{}if(local)personal=mergeRules(personal,local);A.base=base;A.personal=personal;A.rules=mergeRules(base,personal);$('#ruleStatus').className='dot ready';$('#ruleStatusText').textContent=`内置 ${base.adExact.length} + 个人规则`;persist()}catch(e){$('#ruleStatus').className='dot error';$('#ruleStatusText').textContent='规则加载失败';toast(e.message)}}
function counts(){if(!A.rules)return;$('#rAd').textContent=fmt(A.rules.adExact?.length);$('#rGarble').textContent=fmt(A.rules.garbleSamples?.length);$('#rPinyin').textContent=fmt(A.rules.pinyinFixes?.length);$('#rKeep').textContent=fmt((A.rules.keepFields?.length||0)+(A.rules.englishKeep?.length||0)+(A.rules.pinyinKeep?.length||0))}
function worker(type,payload){if(!A.w)A.w=new Worker('./worker.js',{type:'module'});let id=++A.id;return new Promise((ok,no)=>{let h=e=>{if(e.data?.id!==id)return;A.w.removeEventListener('message',h);e.data.ok?ok(e.data.result):no(Error(e.data.error))};A.w.addEventListener('message',h);A.w.postMessage({id,type,...payload})})}
function prog(on,t='正在扫描…',p=10){$('#progressPanel').classList.toggle('hidden',!on);$('#progressText').textContent=t;$('#progressPercent').textContent=p+'%';$('#progressBar').style.width=p+'%'}
function score(s){return(s.match(/[\u3400-\u9fff]/g)||[]).length*.02-(s.match(/�/g)||[]).length*10}
async function decode(f){let b=await f.arrayBuffer(),u=new Uint8Array(b);if(u[0]===0xef&&u[1]===0xbb&&u[2]===0xbf)return{text:new TextDecoder().decode(b),enc:'UTF-8 BOM'};try{return{text:new TextDecoder('utf-8',{fatal:true}).decode(b),enc:'UTF-8'}}catch{}let a=[];for(const e of['gb18030','big5'])try{let t=new TextDecoder(e).decode(b);a.push({text:t,enc:e.toUpperCase(),s:score(t)})}catch{}return a.sort((x,y)=>y.s-x.s)[0]||{text:new TextDecoder().decode(b),enc:'UTF-8'} }
function reset(){A.scan=null;A.groups=[];A.ad={};A.pinyin=null;A.pd={};A.final='';for(const id of['summaryPanel','donePanel','adReviewSection','pinyinReviewSection'])$('#'+id).classList.add('hidden');$('#reviewEmpty').classList.remove('hidden');badge()}
function groups(rows){let m=new Map;for(const x of rows||[]){let g=m.get(x.field)||{field:x.field,kind:x.kind,score:x.score,reason:x.reason,count:0,ctx:x.originalLine};g.count++;g.score=Math.max(g.score,x.score);m.set(x.field,g)}return[...m.values()].sort((a,b)=>b.score-a.score)}
function badge(){let n=A.groups.length+(A.pinyin?.review?.length||0);$('#reviewBadge').textContent=n;$('#reviewBadge').classList.toggle('hidden',!n)}
function adReview(){let r=$('#adReviewList');r.innerHTML='';for(const g of A.groups){A.ad[g.field]??='keep';let e=document.createElement('article');e.className='review-card';e.innerHTML=`<div><div class="field">${esc(g.field)}</div><div class="reason">${esc(g.kind)} · ${g.score.toFixed(1)} · ×${g.count}</div></div><div class="choices"><button data-v="delete">删除</button><button class="active keep" data-v="keep">保留</button></div><div class="context">${esc(g.ctx)}</div>`;let bs=[...e.querySelectorAll('button')];bs.forEach(b=>b.onclick=()=>{A.ad[g.field]=b.dataset.v;bs.forEach(x=>x.classList.toggle('active',x===b))});r.appendChild(e)}$('#adReviewSection').classList.toggle('hidden',!A.groups.length);$('#reviewEmpty').classList.toggle('hidden',!!A.groups.length)}
function pyReview(){let r=$('#pinyinReviewList');r.innerHTML='';for(const [i,c] of(A.pinyin?.review||[]).entries()){A.pd[i]??='keep';let e=document.createElement('article');e.className='review-card';e.innerHTML=`<div><div class="field">${esc(c.original)} → ${esc(c.replacement)}</div><div class="reason">${Math.round(c.confidence*100)}% · ${esc(c.reason)}</div></div><div class="choices"><button data-v="replace">替换</button><button class="active keep" data-v="keep">保留</button><button data-v="english">英文/名称</button></div><div class="context">${esc(c.context)}</div>`;let bs=[...e.querySelectorAll('button')];bs.forEach(b=>b.onclick=()=>{A.pd[i]=b.dataset.v;bs.forEach(x=>x.classList.toggle('active',x===b))});r.appendChild(e)}$('#pinyinReviewSection').classList.toggle('hidden',!(A.pinyin?.review?.length));$('#reviewEmpty').classList.toggle('hidden',!!(A.pinyin?.review?.length)||!!A.groups.length);badge()}
async function scan(){if(!A.file)return;reset();$('#scanBtn').disabled=true;try{prog(1,'识别 TXT 编码…',10);let d=await decode(A.file);A.source=d.text;prog(1,'本地扫描正文…',40);let pubs=$('#publisherInput').value.split(/[,，;；\n]/).map(x=>x.trim()).filter(Boolean);A.scan=await worker('scan',{text:A.source,rules:A.rules,opts:{mode:A.mode,publishers:pubs,preserveBlank:true}});A.groups=groups(A.scan.review);prog(1,'完成',100);setTimeout(()=>prog(0),250);$('#summaryPanel').classList.remove('hidden');$('#summaryTitle').textContent=`${A.file.name} · ${d.enc}`;$('#mAuto').textContent=fmt(A.scan.auto.length);$('#mReview').textContent=fmt(A.groups.length);$('#mPinyinAuto').textContent='—';$('#mPinyinReview').textContent='—';adReview();badge();toast(`自动清理 ${A.scan.auto.length} 处`)}catch(e){prog(0);toast('扫描失败：'+e.message)}finally{$('#scanBtn').disabled=false}}
async function pinyinStage(){if(!A.scan)return;view('review');let sel=A.scan.review.filter(x=>(A.ad[x.field]||'keep')==='delete');let text=applyMatches(A.source,[...A.scan.auto,...sel],true);$('#adReviewSection').classList.add('hidden');if(!$('#pinyinToggle').checked){A.pinyin={text,auto:[],review:[]};return finish()}$('#reviewEmpty').textContent='正在加载离线拼音模型…';try{A.pinyin=await worker('pinyin',{text,rules:A.rules});A.pd={};$('#mPinyinAuto').textContent=fmt(A.pinyin.auto.length);$('#mPinyinReview').textContent=fmt(A.pinyin.review.length);pyReview();if(!A.pinyin.review.length)finish()}catch(e){toast('拼音修复失败：'+e.message);A.pinyin={text,auto:[],review:[]};finish()}}
function addFix(f){if(!f?.source||!f?.target)return 0;A.rules.pinyinFixes??=[];let x=A.rules.pinyinFixes.find(z=>z.source===f.source&&z.target===f.target);if(x){x.count=(x.count||1)+1;return 0}A.rules.pinyinFixes.push({source:f.source,target:f.target,count:1});return 1}
function learn(){let n=0,gar=new Set(['pollution','obfuscated_ad','standalone_pollution_line','pollution_prefix','group_context_ad']);for(const m of A.scan?.auto||[]){if(m.kind==='learned_exact'||['html_tag','web_link','roman_numeral'].includes(m.kind))continue;let a=gar.has(m.kind)?(A.rules.garbleSamples??=[]):(A.rules.adExact??=[]);if(!a.includes(m.field)){a.push(m.field);n++}}for(const g of A.groups){let v=A.ad[g.field]||'keep';if(v==='delete'){let a=gar.has(g.kind)?(A.rules.garbleSamples??=[]):(A.rules.adExact??=[]);if(!a.includes(g.field)){a.push(g.field);n++}}else{A.rules.keepFields??=[];if(!A.rules.keepFields.includes(g.field)){A.rules.keepFields.push(g.field);n++}}}for(const c of A.pinyin?.auto||[])n+=addFix(c.learnFix||{source:c.original,target:c.replacement});for(const[k,v]of Object.entries(A.pd)){let c=A.pinyin?.review?.[+k];if(!c)continue;if(v==='replace')n+=addFix(c.learnFix||contextualFix(c,c.context||''));else if(v==='english'){A.rules.englishKeep??=[];if(!A.rules.englishKeep.some(x=>x.toLowerCase()===c.original.toLowerCase())){A.rules.englishKeep.push(c.original);n++}}else{A.rules.pinyinKeep??=[];let q=c.learnFix?.source||c.original;if(!A.rules.pinyinKeep.includes(q)){A.rules.pinyinKeep.push(q);n++}}}A.rules.stats??={};A.rules.stats.learnedBooks=(A.rules.stats.learnedBooks||0)+1;dirty(Math.max(1,n));return n}
function finish(){A.final=applyPinyinReview(A.pinyin.text,A.pinyin.review||[],A.pd);let n=learn();$('#pinyinReviewSection').classList.add('hidden');$('#donePanel').classList.remove('hidden');$('#doneText').textContent=`处理完成；本次新增/确认学习约 ${n} 条。小说正文未上传。`;view('clean');badge()}
function dl(c,n,t='text/plain;charset=utf-8'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c],{type:t}));a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800)}
function renderRules(){counts();let q=$('#ruleSearch').value.trim().toLowerCase(),r=[];for(const x of A.rules?.adExact||[])r.push(['广告',x]);for(const x of A.rules?.garbleSamples||[])r.push(['乱码',x]);for(const x of A.rules?.pinyinFixes||[])r.push(['拼音',`${x.source} → ${x.target} ×${x.count||1}`]);for(const x of A.rules?.englishKeep||[])r.push(['英文',x]);$('#ruleList').innerHTML=r.filter(x=>!q||x.join(' ').toLowerCase().includes(q)).slice(0,800).map(x=>`<div class="rule-row"><span>${x[0]}</span><code>${esc(x[1])}</code></div>`).join('')||'<div class="empty">没有匹配规则</div>'}
function cfg(){return{repo:$('#repoInput').value.trim(),branch:$('#branchInput').value.trim()||'main',token:$('#tokenInput').value.trim()}}
function saveCfg(){localStorage.setItem(LG,JSON.stringify(cfg()))}function loadCfg(){try{let c=JSON.parse(localStorage.getItem(LG)||'null');if(c){$('#repoInput').value=c.repo||$('#repoInput').value;$('#branchInput').value=c.branch||'main';$('#tokenInput').value=c.token||''}}catch{}}
const gh=t=>({'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(t?{Authorization:`Bearer ${t}`}:{})});
function b64(s){let u=new TextEncoder().encode(s),z='';for(let i=0;i<u.length;i+=32768)z+=String.fromCharCode(...u.subarray(i,i+32768));return btoa(z)}function unb64(s){let b=atob(s.replace(/\s/g,'')),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return new TextDecoder().decode(u)}
async function remote(c){let [o,r]=c.repo.split('/'),url=`https://api.github.com/repos/${o}/${r}/contents/rules.json?ref=${c.branch}`,x=await fetch(url,{headers:gh(c.token),cache:'no-store'});if(!x.ok)throw Error(`读取 rules.json HTTP ${x.status}`);let j=await x.json();return{rules:JSON.parse(unb64(j.content)),sha:j.sha,url:`https://api.github.com/repos/${o}/${r}/contents/rules.json`}}
async function saveGit(){let c=cfg();if(!c.token){view('settings');return toast('请填写 Fine-grained Token')}saveCfg();try{$('#gitResult').textContent='正在合并 GitHub 最新规则…';let r=await remote(c),p=subtract(A.rules,A.base),m=mergeRules(r.rules,p);m.version=Math.max(+r.rules.version||0,+p.version||0)+1;m.updatedAt=new Date().toISOString();let x=await fetch(r.url,{method:'PUT',headers:{...gh(c.token),'Content-Type':'application/json'},body:JSON.stringify({message:`rules: update personal learning v${m.version}`,content:b64(JSON.stringify(m,null,2)),sha:r.sha,branch:c.branch})});if(!x.ok)throw Error(`写入 HTTP ${x.status}`);A.personal=m;A.rules=mergeRules(A.base,m);A.dirty=0;localStorage.setItem(LS,JSON.stringify(m));$('#pendingSync').textContent='待同步 0';$('#pendingSync').classList.remove('dirty');$('#gitResult').textContent=`保存成功：rules.json v${m.version}`;toast('规则已保存到 GitHub')}catch(e){$('#gitResult').textContent='保存失败：'+e.message;toast('GitHub 保存失败')}}
async function pullGit(){let c=cfg();saveCfg();try{let r=await remote(c);A.personal=r.rules;A.rules=mergeRules(A.base,r.rules);A.dirty=0;localStorage.setItem(LS,JSON.stringify(r.rules));counts();$('#gitResult').textContent=`已恢复 rules.json v${r.rules.version||1}`;toast('规则恢复完成')}catch(e){$('#gitResult').textContent='恢复失败：'+e.message}}
async function testGit(){let c=cfg();saveCfg();try{let r=await fetch(`https://api.github.com/repos/${c.repo}`,{headers:gh(c.token)});if(!r.ok)throw Error(`HTTP ${r.status}`);let j=await r.json();$('#gitResult').textContent=`连接成功：${j.full_name}`}catch(e){$('#gitResult').textContent='连接失败：'+e.message}}
function bind(){$$('.tab').forEach(b=>b.onclick=()=>view(b.dataset.view));$('#backCleanBtn').onclick=()=>view('clean');$$('#modeGroup button').forEach(b=>b.onclick=()=>{$$('#modeGroup button').forEach(x=>x.classList.toggle('active',x===b));A.mode=b.dataset.mode});$('#fileInput').onchange=()=>{let f=$('#fileInput').files?.[0];if(!f)return;A.file=f;reset();$('#fileTitle').textContent=f.name;$('#fileMeta').textContent=`${(f.size/1048576).toFixed(2)} MB · 仅本地读取`;$('#scanBtn').disabled=false};$('#scanBtn').onclick=scan;$('#goReviewBtn').onclick=()=>{view('review');A.groups.length?adReview():pinyinStage()};$('#keepAllAdBtn').onclick=()=>{for(const g of A.groups)A.ad[g.field]='keep';adReview()};$('#applyAdBtn').onclick=pinyinStage;$('#keepAllPinyinBtn').onclick=()=>{(A.pinyin?.review||[]).forEach((_,i)=>A.pd[i]='keep');pyReview()};$('#finishBtn').onclick=finish;$('#downloadBtn').onclick=()=>{if(A.final){let n=(A.file?.name||'novel.txt').replace(/\.txt$/i,'');dl('\ufeff'+A.final,`${n}_去广告.txt`)}};$('#saveGitQuickBtn').onclick=saveGit;$('#ruleSearch').oninput=renderRules;$('#exportRulesBtn').onclick=()=>dl(JSON.stringify(subtract(A.rules,A.base),null,2),'rules.json','application/json;charset=utf-8');$('#importRulesInput').onchange=async()=>{let f=$('#importRulesInput').files?.[0];if(!f)return;try{A.rules=mergeRules(A.rules,JSON.parse(await f.text()));dirty(1);renderRules()}catch{toast('无效 rules.json')}};for(const id of['repoInput','branchInput','tokenInput'])$('#'+id).onchange=saveCfg;$('#testGitBtn').onclick=testGit;$('#saveGitBtn').onclick=saveGit;$('#pullGitBtn').onclick=pullGit}
async function boot(){bind();loadCfg();await loadRules();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn)}boot();
